import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Banner } from '@/components/Banner';
import StoreProvider from './storeProvider';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Virtual Clinic',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider initialChatId="normal">
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <Banner />
                    {children}
                </body>
            </html>
        </StoreProvider>
    );
}
